services:
  pg-1:
    image: postgres:15
    container_name: pg-1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - pg1_data:/var/lib/postgresql/data

  pg-2:
    image: postgres:15
    container_name: pg-2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - pg2_data:/var/lib/postgresql/data

  shipment-service:
    image: turkcell-shipment-service
    container_name: shipment_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_UR: "jdbc:postgresql://pg-2:5432/shipment-service"


  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  pg1_data:
  pg2_data:
